#!/usr/bin/env python3
"""
train_random_forest.py
======================
Train a Random Forest classifier (and optionally other models) on the
preprocessed FANET DoS dataset.

Inputs  (generated by preprocessing.py):
  ml/models/X_train.npy
  ml/models/y_train.npy
  ml/models/feature_names.txt

Outputs:
  ml/models/random_forest.pkl
  ml/models/feature_importance.csv
  results/graphs/feature_importance.png  (if matplotlib available)

Usage:
  python train_random_forest.py [--n_estimators 200] [--max_depth 20]
"""

import argparse
import os
import pickle

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold

# Optional visualisation
try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    HAS_MPL = True
except ImportError:
    HAS_MPL = False


# ---------------------------------------------------------------------------
MODELS_DIR  = os.path.join(os.path.dirname(__file__), "models")
RESULTS_DIR = os.path.join(os.path.dirname(__file__), "..", "results", "graphs")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Train Random Forest for FANET DoS detection"
    )
    parser.add_argument("--n_estimators", type=int,   default=200,
                        help="Number of trees (default: 200)")
    parser.add_argument("--max_depth",    type=int,   default=None,
                        help="Max tree depth (default: unlimited)")
    parser.add_argument("--min_samples_leaf", type=int, default=1,
                        help="Min samples per leaf (default: 1)")
    parser.add_argument("--cv_folds",     type=int,   default=5,
                        help="Cross-validation folds (default: 5)")
    parser.add_argument("--seed",         type=int,   default=42,
                        help="Random seed")
    parser.add_argument("--no_cv",        action="store_true",
                        help="Skip cross-validation (faster)")
    return parser.parse_args()


# ---------------------------------------------------------------------------
def load_data():
    X_train = np.load(os.path.join(MODELS_DIR, "X_train.npy"))
    y_train = np.load(os.path.join(MODELS_DIR, "y_train.npy"))

    feature_path = os.path.join(MODELS_DIR, "feature_names.txt")
    if os.path.exists(feature_path):
        with open(feature_path) as f:
            feature_names = [line.strip() for line in f if line.strip()]
    else:
        feature_names = [f"f{i}" for i in range(X_train.shape[1])]

    return X_train, y_train, feature_names


def plot_feature_importance(clf, feature_names):
    os.makedirs(RESULTS_DIR, exist_ok=True)
    importances = clf.feature_importances_
    indices     = np.argsort(importances)[::-1]
    top_n       = min(20, len(feature_names))

    if HAS_MPL:
        fig, ax = plt.subplots(figsize=(10, 6))
        ax.barh(
            [feature_names[i] for i in indices[:top_n]][::-1],
            importances[indices[:top_n]][::-1],
        )
        ax.set_xlabel("Importance")
        ax.set_title("Random Forest – Top Feature Importances")
        plt.tight_layout()
        out_path = os.path.join(RESULTS_DIR, "feature_importance.png")
        plt.savefig(out_path, dpi=150)
        plt.close()
        print(f"[OK] Feature importance plot saved to {out_path}")

    # Always save CSV
    fi_df = pd.DataFrame({
        "feature":    [feature_names[i] for i in indices],
        "importance": importances[indices],
    })
    csv_path = os.path.join(MODELS_DIR, "feature_importance.csv")
    fi_df.to_csv(csv_path, index=False)
    print(f"[OK] Feature importance CSV saved to {csv_path}")

    print("\nTop-10 features:")
    for i in indices[:10]:
        print(f"  {feature_names[i]:<30s} {importances[i]:.4f}")


# ---------------------------------------------------------------------------
def main():
    args = parse_args()
    os.makedirs(MODELS_DIR, exist_ok=True)

    X_train, y_train, feature_names = load_data()
    print(f"[INFO] Training set: {X_train.shape[0]} samples, "
          f"{X_train.shape[1]} features")
    print(f"[INFO] Label distribution: "
          f"normal={int((y_train==0).sum())}  "
          f"attack={int((y_train==1).sum())}")

    # ------------------------------------------------------------------
    # Cross-validation
    # ------------------------------------------------------------------
    clf = RandomForestClassifier(
        n_estimators      = args.n_estimators,
        max_depth         = args.max_depth,
        min_samples_leaf  = args.min_samples_leaf,
        n_jobs            = -1,
        random_state      = args.seed,
        class_weight      = "balanced",
    )

    if not args.no_cv:
        cv = StratifiedKFold(n_splits=args.cv_folds, shuffle=True,
                             random_state=args.seed)
        cv_scores = cross_val_score(clf, X_train, y_train,
                                    cv=cv, scoring="f1", n_jobs=-1)
        print(f"\n[CV]  F1 per fold : {np.round(cv_scores, 4)}")
        print(f"[CV]  Mean F1      : {cv_scores.mean():.4f} "
              f"± {cv_scores.std():.4f}")

    # ------------------------------------------------------------------
    # Final fit on full training set
    # ------------------------------------------------------------------
    print("\n[INFO] Training final model on full training set …")
    clf.fit(X_train, y_train)

    # ------------------------------------------------------------------
    # Save model
    # ------------------------------------------------------------------
    model_path = os.path.join(MODELS_DIR, "random_forest.pkl")
    with open(model_path, "wb") as f:
        pickle.dump(clf, f)
    print(f"[OK] Model saved to {model_path}")

    # ------------------------------------------------------------------
    # Feature importance
    # ------------------------------------------------------------------
    plot_feature_importance(clf, feature_names)


if __name__ == "__main__":
    main()
